const gites_en = [
	{
		lodge: {
			name: 'The Lodge',
			description: '2 habitaciones dobles con baño privado',
			shortName: 'lodge',
			imageFileName: '01_lodge_bedroom1',
			content:
				"The Lodge es una propiedad de alquiler de lujo que ofrece a los huéspedes dos habitaciones dobles bellamente diseñadas. Cada dormitorio encantador tiene ropa de cama de alta calidad y almohadas de plumas de ganso, con productos de ducha en todos los baños. The Lodge cuenta con calefacción/refrigeración por suelo radiante, TV/DVD de 43''/108 cm con canales internacionales, Amazon Prime y Netflix, así como acceso Wi-Fi en el interior y en el jardín. \n \n El primer dormitorio está decorado en estilo Steampunk está climatizado y dispone de una cama de 180x200. El baño tiene un lavabo con doble pila, una gran ducha a ras de suelo y espejos iluminados. El segundo dormitorio se encuentra en la planta baja con una cama de 160x200 y calefacción/refrigeración por suelo radiante. El baño tiene un mueble de baño, ducha grande y espejos iluminados. La cocina de The Lodge está totalmente equipada con hornos, lavavajillas, frigorífico/congelador, cafetera espresso y mucho más. La cocina tiene encimeras de piedra y mucho espacio para que los huéspedes preparen sus comidas favoritas. Se proporciona una lavadora/secadora para estancias más largas. \n \n El área exterior de The Lodge está bellamente ajardinada con una piscina privada climatizada de agua salada, un cenador con una mesa de comedor de alta calidad, un área para tomar el sol con tumbonas, una plancha, vistas al bosque y las magníficas puestas de sol al oeste. El jardín también tiene iluminación ambiental por la noche, lo que lo convierte en un excelente lugar para relajarse y disfrutar del hermoso entorno.",
			information: {
				facilities: [
					'Todos los dormitorios tienen baños completamente alicatados',
					'Ropa de cama de algodón de alta calidad con almohadas de plumas de ganso (camas hechas a la llegada)',
					'Artículos de tocador (champú/gel de ducha) en todos los baños',
					'Paquete de bienvenida para ayudarlo a comenzar',
					'Adaptadores eléctricos internacionales',
					'Caja fuerte para objetos de valor codificada digitalmente',
					'Altavoz Bluetooth Bose',
					'Suelo radiante (calor)',
					'Camas 180x200 o 160/200',
					"TV de pantalla plana de 43''/108 cm con Internet/canales internacionales, Amazon Prime y Netflix",
					'Wi-Fi (interior y en el jardín)',
					'Toallas de piscina proporcionadas',
				],
				suites: [
					{
						theme: 'Suite Steampunk',
						facilities: [
							'1er piso / 21m2',
							'Cama de 180x200cm',
							'Aire acondicionado',
							'Edredones, almohadas y ropa de cama de alta calidad',
							'Muebles de roble, incluidos armario, cómoda y mesitas de noche steampunk hechas a medida',
							'Radio despertador con cargador inalámbrico/USB',
							'Cortinas opacas',
							'Secador de pelo',
							'Mueble de lavabo doble con mucho espacio de almacenamiento',
							'Toallas de alta calidad, incluida una gran toalla de baño',
							'Secador de toallas',
							'Ducha a ras de suelo grande con ducha termostática de efecto lluvia y dispensadores de artículos de tocador montados en la pared',
							'Espejo de aumento iluminado',
							'Gran espejo anti vaho e iluminado',
						],
					},
					{
						theme: 'Dormitorio en la planta baja',
						facilities: [
							'Planta baja / 16m2',
							'Cama de 160x200cm',
							'Suelo radiante (calor/frio)',
							'Edredones, almohadas y ropa de cama de alta calidad',
							'Dormitorio de roble macizo',
							'Radio despertador con cargador inalámbrico/USB',
							'Cortinas opacas',
							'Secador de pelo',
							'Mueble de lavabo con mucho espacio de almacenamiento',
							'Toallas de alta calidad, incluida una gran toalla de baño',
							'Secador de toallas',
							'Ducha italiana grande con ducha termostática de efecto lluvia y dispensadores de artículos de tocador montados en la pared',
							'Espejo iluminado',
							'Espejo de aumento iluminado',
						],
					},
				],
				kitchen: {
					information:
						'The Lodge ofrece una deliciosa y espaciosa cocina con encimeras de Silestone y mucho espacio para preparar sus comidas favoritas. Está muy bien equipada con electrodomésticos de calidad y todo lo necesario para su estancia incluyendo:',
					facilities: [
						'Cocina Falcon Kitchener con campana extractora',
						'Lavavajillas Bosch',
						'Nevera/congelador Whirlpool',
						'Lavavajillas Whirlpool',
						'Cafetera exprés',
						'Hervidor eléctrico de agua',
						'Microondas',
						'Exprimidor eléctrico',
						'Batidor eléctrico',
						'Cafetera',
						'Tostadora',
						'Una amplia selección de cubiertos, vasos, utensilios y vajilla Denby',
					],
				},
				garden: [
					'Jardín paisajístico con iluminación ambiental nocturna',
					'Piscina privada y climatizada de agua salada',
					'Cenador con elegante mesa de comedor y sillas/cojines (para 6). Iluminación ambiental/comedor con control remoto',
					'Terraza/solarium con tumbonas/cojines',
					'Plancha',
					'¡Vistas al bosque y hermosos atardeceres del oeste!',
				],
			},
		},
	},
	{
		barn: {
			name: 'The Barn',
			description: '3 dormitorios dobles con baño',
			shortName: 'barn',
			imageFileName: 'barn-bedroom-area',
			content:
				'The Barn es una lujosa propiedad de vacaciones con tres amplias habitaciones dobles, cada una con baño en suite. Cada habitación está bellamente diseñada con su propio tema, que incluye Animal Magic, Modern Chic y French Chic, y brinda una experiencia vacacional lujosa e inolvidable. The Barn ofrece instalaciones de primera línea que incluyen ropa de cama de alta calidad con almohadas de plumas de ganso, productos de ducha en cada baño y suelo radiante en toda la planta baja. Además, cuenta con una amplia cocina totalmente equipada con cocina de gama, lavavajillas, cafetera espresso y otros elementos esenciales para cocinar. El jardín es un paraíso tranquilo con piscina privada climatizada de agua salada, cenador, terraza y plancha. El jardín también tiene iluminación ambiental por la noche y ofrece impresionantes vistas del bosque y las puestas de sol hacia el oeste. Con Wi-Fi en el interior y en el jardín, adaptadores eléctricos internacionales proporcionados y un paquete de bienvenida para comenzar, The Barn es la escapada perfecta para unas vacaciones relajantes y rejuvenecedoras.',
			information: {
				facilities: [
					'Todas las habitaciones tienen baños con azulejos (aire acondicionado en el primer piso)',
					'Ropa de cama de algodón de alta calidad con almohadas de plumas de ganso (hechas a la llegada)',
					'Artículos de tocador (champú/gel de ducha) en todos los baños',
					'Paquete de bienvenida para ayudarlo a comenzar',
					'Mesa de comedor con capacidad para ocho personas',
					'Adaptadores eléctricos internacionales',
					'Caja fuerte para objetos de valor codificada digitalmente',
					'Altavoz Bluetooth JBL',
					'Calefacción/refrigeración por suelo radiante en toda la planta baja',
					'Camas 18x200 o 160x200',
					"TV de pantalla plana de 43''/108 cm con Internet/canales internacionales",
					'Wi-Fi (interior y en el jardín)',
					'Toallas de piscina disponibles gratuitamente',
				],
				suites: [
					{
						theme: 'Suite Fauna Mágica',
						facilities: [
							'1er piso / 31m2',
							'Cama de 180x200cm',
							'Aire acondicionado',
							"TV de pantalla plana de 43''/108 cm con Internet/canales internacionales",
							'Edredones, almohadas y ropa de cama de alta calidad',
							'Muebles de roble de calidad, incluidos armario, cómoda y mesitas de noche',
							'Radio despertador con cargador inalámbrico/USB',
							'Mueble de baño con doble pila con mucho espacio de almacenamiento',
							'Toallas de alta calidad, incluida una gran toalla de baño',
							'Secador de toallas',
							'Ducha a ras de suelo grande con ducha termostática de efecto lluvia y dispensadores de artículos de tocador montados en la pared',
							'Espejo de aumento iluminado',
							'Secador de pelo',
							'WC separado',
							'¡Ventana de techo Velux para ver las estrellas! (con persiana eléctrica)',
						],
					},
					{
						theme: 'Suite moderna y elegante',
						facilities: [
							'Planta baja / 21m2',
							'Cama de 160x200cm',
							'Calefacción por suelo radiante (o refrigeración)',
							'Edredones, almohadas y ropa de cama de alta calidad',
							'Muebles de dormitorio de roble macizo',
							'Radio despertador con cargador inalámbrico/USB',
							'Cortinas opacas',
							'Secador de pelo',
							'Puertas de 90 cm de ancho con picaportes bajos',
							'Asideros para la ducha y el inodoro',
							'Mampara de ducha plegable',
							'Asiento de ducha disponible',
							'Mueble de lavabo doble con mucho espacio de almacenamiento',
							'Toallas de alta calidad, incluida una gran toalla de baño',
							'Secador de toallas',
							'Gran espejo anti vaho e iluminado',
							'Ducha italiana grande con ducha termostática de efecto lluvia y dispensadores de artículos de tocador montados en la pared',
						],
					},
					{
						theme: 'Suite French Chic',
						facilities: [
							'Planta baja / 13m2',
							'Cama de 160x200cm',
							'Calefacción por suelo radiante (o refrigeración)',
							'Edredones, almohadas y ropa de cama de alta calidad',
							'Armario, cómoda, mesitas de noche en roble macizo',
							'Radio despertador con cargador inalámbrico/USB',
							'Cortinas opacas',
							'Secador de pelo',
							'Acceso directo al jardín',
							'Mueble de baño con doble pila y con mucho espacio de almacenamiento',
							'Toallas de alta calidad, incluida una gran toalla de baño',
							'Secador de toallas',
							'Ducha a ras de suelo grande con ducha termostática de efecto lluvia y dispensadores de artículos de tocador montados en la pared',
							'Gran espejo anti vaho e iluminado',
						],
					},
				],
				kitchen: {
					information:
						'The Barn tiene una cocina a medida con encimera de granito. Está muy bien equipada con electrodomésticos de calidad y todo lo necesario para su estancia, entre ellos:',
					facilities: [
						'Cocina Falcon Kitchener Range con campana extractora Electrolux',
						'Lavavajillas Bosch',
						'Frigorífico/congelador Whirlpool con dispensador de agua',
						'Lavadora/secadora LG',
						'una cafetera espresso',
						'Hervidor eléctrico de agua ',
						'Microondas',
						'Batidora/batidora eléctrica',
						'Exprimidor eléctrico',
						'Cafetera',
						'Tostadora',
						'Botellero de roble',
						'Una amplia selección de cubiertos, vasos, utensilios y vajilla Denby',
					],
				},
				garden: [
					'Jardín paisajístico con iluminación ambiental nocturna',
					'Piscina privada y climatizada de agua salada',
					'Cenador con elegante mesa de comedor y sillas/cojines (para 8). Iluminación ambiental/comedor con control remoto',
					'Terraza/solarium con tumbonas/cojines',
					'Plancha',
					'¡Vistas al bosque y hermosos atardeceres del oeste!',
				],
			},
		},
	},
];

export default async function getGites(req, res) {
	res.status(200).json(gites_en);
}
