const gites_en = [
	{
		lodge: {
			name: 'The Lodge',
			description: '2 Double Ensuite Bedrooms',
			shortName: 'lodge',
			imageFileName: '01_lodge_bedroom1',
			content:
				"The Lodge is a luxury rental property that offers guests two beautifully designed double ensuite bedrooms. Each delightful bedroom boasts high-quality bedding and goose feather pillows, with shower products provided in all bathrooms. The Lodge features underfloor heating and cooling, a 43”/108cm TV/DVD with international channels, Amazon Prime and Netflix as well as Wi-Fi access both inside and in the garden. \n \n The first bedroom is themed in a Steampunk style and is air-conditioned with a super-king sized bed. The bathroom features a double sink unit, large walk-in shower, and illuminated mirrors. The second bedroom is located on the ground floor with a queen sized bed and underfloor heating. The room features a vanity unit, large wet room shower, and illuminated mirrors. The Lodge's kitchen is fully equipped with a range cooker, dishwasher, fridge/freezer, espresso maker, and more. The kitchen features stone worktops and plenty of space for guests to prepare their favourite dishes. A washer/dryer is provided for longer stays. \n \n The Lodge's outdoor space is beautifully landscaped with a private heated saltwater plunge pool, a gazebo with high-quality dining table, a sunbathing area with chaise longues, a plancha, and views of the forest and stunning sunsets to the west. The garden also features night time mood lighting, making it an ideal place to relax and enjoy the beautiful surroundings.",
			information: {
				facilities: [
					'All en-suite bedrooms with fully tiled bathrooms',
					'High quality cotton bedding with goose feather pillows (made up when you arrive)',
					'Toiletries (shampoo/bodywash) provided in all bathrooms',
					'Welcome pack to get you up and running',
					'International power adapters',
					'Numeric code valuables safe',
					'Bose bluetooth speaker',
					'Underfloor heating',
					'Super-king or queen sized beds',
					'43”/108cm flat-screen TV with internet/international channels, Amazon Prime and Netflix',
					'WiFi (Inside and in the garden)',
					'Pool towels provided',
				],
				suites: [
					{
						theme: 'Steampunk Suite',
						facilities: [
							'1st floor / 21m2',
							'Super-king / 180cm bed',
							'Air-conditioned',
							'High-quality duvet, pillows and bed linen',
							'Oak furniture including wardrobe, chest of drawers and custom, steam-punk bedside tables',
							'Clock radio with wireless charging/USB',
							'Blackout curtains',
							'Hairdryer',
							'Double sink unit with lots of storage',
							'High quality towels including large bath sheet',
							'Heated towel rail',
							'Large walk-in shower with thermostatic rainfall shower and wall-mounted toiletry dispensers',
							'Illuminated magnifying mirror',
							'Large heated and illuminated mirror',
						],
					},
					{
						theme: 'Ground floor bedroom suite ',
						facilities: [
							'Ground floor / 16m2',
							'Queen / 160cm bed',
							'Underfloor heating (and cooling)',
							'High-quality duvet, pillows and bed linen',
							'Solid oak bedroom suite',
							'Clock radio with wireless charging/USB',
							'Blackout curtains',
							'Hairdryer',
							'Vanity unit with lots of storage',
							'High quality towels including large bath sheet',
							'Heated towel rail',
							'Large, walk-in wet room shower with thermostatic rainfall shower and wall-mounted toiletry dispensers',
							'Illuminated mirror',
							'Illuminated magnifying mirror',
						],
					},
				],
				kitchen: {
					information:
						'The Lodge offers a delightful, spacious kitchen featuring Silestone worktops and plenty of space for preparing your favourite dishes. It is very well equipped with quality appliances and all the necessities for your stay including:',
					facilities: [
						'Falcon Kitchener Range cooker with extractor hood',
						'Bosch Dishwasher',
						'Whirlpool Fridge/Freezer',
						'Whirlpool Washer/dryer',
						'Espresso coffee maker',
						'Kettle',
						'Microwave',
						'Electric juice maker',
						'Electric whisk',
						'Cafetiere',
						'Toaster',
						'A wide selection of cutlery, glasses, utensils and Denby crockery',
					],
				},
				garden: [
					'Landscaped garden with night time mood lighting',
					'Private, heated, salt water plunge pool',
					'Gazebo with elegant dining table and chairs/cushions (for 6).  Remote control mood/dining lighting',
					'Terrace/sunbathing area with chaises longues/cushions',
					'Barbeque/Plancha',
					'Views to the forest and stunning sunsets to the west!',
				],
			},
		},
	},
	{
		barn: {
			name: 'The Barn',
			description: '3 Double Ensuite Bedrooms',
			shortName: 'barn',
			imageFileName: 'barn-bedroom-area',
			content:
				'The Barn is a luxurious holiday property with three spacious double en-suite bedrooms. Each room is beautifully designed with its own theme including Animal Magic, Modern Chic and French Chic and  provides a luxurious and unforgettable holiday experience. The Barn offers top-of-the-line facilities including high-quality bedding with goose feather pillows, all en-suite bedrooms with shower products provided in each bathroom together with underfloor heating throughout the ground floor. Additionally, it has a large, fully equipped kitchen with a range cooker, dishwasher, espresso maker, and other essentials for cooking. The garden is a tranquil paradise with a private, heated salt water plunge pool, gazebo, terrace, and plancha. The garden also features night time mood lighting and offers stunning views of the forest and sunsets to the west. With WiFi inside and in the garden, international power adapters provided and a welcome pack to get you started, The Barn is the perfect getaway for a relaxing and rejuvenating vacation.',
			information: {
				facilities: [
					'All en-suite bedrooms with fully tiled bathrooms (Air-conditioning to 1st floor)',
					'High quality cotton bedding with goose feather pillows (made up when you arrive)',
					'Toiletries (shampoo/bodywash) provided in all bathrooms',
					'Welcome pack to get you up and running',
					'Dining table for up to eight',
					'International power adapters',
					'Numeric code valuables safe',
					'JBL bluetooth speaker',
					'Underfloor heating (and cooling) throughout ground floor',
					'Super-king or queen sized beds',
					'43”/108cm flat-screen TV with internet/international channels',
					'WiFi (Inside and in the garden)',
					'Pool towels provided',
				],
				suites: [
					{
						theme: 'Animal Magic Suite',
						facilities: [
							'1st floor / 31m2',
							'Super-king / 180cm bed',
							'Air-conditioned',
							'43”/108cm flat-screen TV with internet/international channels',
							'High-quality duvet, pillows and bed linen',
							'Quality oak furniture including wardrobe, chest of drawers and bedside cabinets',
							'Clock radio with wireless charging/USB',
							"Jack 'n' Jill sink unit with lots of storage",
							'High quality towels including large bath sheet',
							'Heated towel rail',
							'Large walk-in shower with thermostatic rainfall shower and wall-mounted toiletry dispensers',
							'Illuminated magnifying mirror',
							'Hairdryer',
							'Separate toilet',
							'Velux roof window to watch the stars! (with electric blind)',
						],
					},
					{
						theme: 'Modern Chic Suite',
						information:
							'This room has been adapted for disabled use as far as possible within the bounds of the existing building.  The Barn’s garden is accessed via a ramp and a ramp is available for access to the main door.',
						facilities: [
							'Ground floor / 21m2',
							'Queen / 160cm bed',
							'Underfloor heating (or cooling)',
							'High-quality duvet, pillows and bed linen',
							'Solid oak bedroom furniture',
							'Clock radio with wireless charging/USB',
							'Blackout curtains',
							'Hairdryer',
							'90cm wide doors with lowered handles',
							'Grab handles for shower and toilet',
							'Folding shower screen',
							'Shower seat available',
							'Double sink unit with lots of storage',
							'High quality towels including large bath sheet',
							'Heated towel rail',
							'Large heated and illuminated mirror',
							'Large, walk-in wet room shower with thermostatic rainfall shower and wall-mounted toiletry dispensers',
						],
					},
					{
						theme: 'French Chic Suite',
						facilities: [
							'Ground floor / 13m2',
							'Queen / 160cm bed',
							'Underfloor heating (or cooling)',
							'High-quality duvet, pillows and bed linen',
							'Solid oak wardrobe, chest of drawers, bedside tables',
							'Clock radio with wireless charging/USB',
							'Blackout curtains',
							'Hairdryer',
							'Direct access to the garden',
							'Double sink unit with lots of storage',
							'High quality towels including large bath sheet',
							'Heated towel rail',
							'Large, walk-in wet room shower with thermostatic rainfall shower and wall-mounted toiletry dispensers',
							'Large heated and illuminated mirror',
						],
					},
				],
				kitchen: {
					information:
						'The Barn is fitted with a custom kitchen with granite worktops.  It is very well equipped with quality appliances and all the necessities for your stay, including:',
					facilities: [
						'Falcon Kitchener Range cooker with Electrolux extractor hood',
						'Bosch Dishwasher',
						'Whirlpool Fridge/Freezer with water dispenser',
						'LG Washer/dryer',
						'Espresso coffee maker',
						'Kettle',
						'Microwave',
						'Electric whisk/blender',
						'Electric juice maker',
						'Cafetiere',
						'Toaster',
						'Oak wine-rack',
						'A wide selection of cutlery, glasses, utensils and Denby crockery',
					],
				},
				garden: [
					'Landscaped garden with night time mood lighting',
					'Private, heated, salt water plunge pool',
					'Gazebo with elegant dining table and chairs/cushions (for 8).  Remote control mood/dining lighting',
					'Terrace/sunbathing area with chaises longues/cushions',
					'Barbeque/Plancha',
					'Views to the forest and stunning sunsets to the west!',
				],
			},
		},
	},
];

export default async function getGites(req, res) {
	res.status(200).json(gites_en);
}
