const gites_en = [
	{
		lodge: {
			name: 'The Lodge',
			description: '2 chambres doubles avec salle de bains',
			shortName: 'lodge',
			imageFileName: '01_lodge_bedroom1',
			content:
				"The Lodge est une propriété locative de luxe qui offre à ses clients deux chambres doubles magnifiquement conçues. Chaque charmante chambre dispose d'une literie de haute qualité et d'oreillers en plumes d'oie, avec des produits de douche fournis dans toutes les salles de bains. The Lodge dispose de plancher chauffant/rafraichissant, d'une télévision/DVD 43''/108cm avec chaînes internationales, Amazon Prime et Netflix ainsi que d'un accès Wi-Fi à l'intérieur et dans le jardin. \n \n La première chambre est décorée dans un style Steampunk et est climatisée avec un lit de dimensions 180x200. La salle de bain dispose d'un meuble double vasque, d'une grande douche à l'italienne et de miroirs éclairés. La deuxième chambre est située au rez-de-chaussée avec un lit 160x200 et le chauffage au sol. La chambre dispose d'un meuble vasque, d'une grande douche et de miroirs éclairés. La cuisine du gîte The Lodge est entièrement équipée avec une cuisinière, un lave-vaisselle, un réfrigérateur/congélateur, une machine à expresso et bien plus encore. La cuisine dispose de plans de travail en pierre et de beaucoup d'espace pour que les invités puissent préparer leurs plats préférés. Un lave-linge/sèche-linge est fourni pour les longs séjours. \n \n L'espace extérieur du gîte The Lodge est magnifiquement aménagé avec une piscine d'eau salée chauffée privée, un kiosque avec une table à manger de haute qualité, un espace de bronzage avec des chaises longues, une plancha, une vue sur la forêt et les magnifiques couchers de soleil à l'ouest. Le jardin dispose également d'un éclairage d'ambiance nocturne, ce qui en fait un endroit idéal pour se détendre et profiter du cadre magnifique.",
			information: {
				facilities: [
					'Toutes les chambres ont des salles de bains entièrement carrelées',
					"Literie en coton de grande qualité avec oreillers en plumes d'oie (faits à votre arrivée)",
					'Articles de toilette (shampooing/gel douche) fournis dans toutes les salles de bains',
					'Pack de bienvenue pour vous aider à démarrer',
					'Adaptateurs électriques internationaux',
					'Coffre-fort pour objets de valeur à code numérique',
					'Enceinte Bluetooth Bose',
					'Plancher chauffant',
					'Lits 180x200 ou 160/200',
					"Télévision à écran plat 43''/108 cm avec chaînes Internet/internationales, Amazon Prime et Netflix",
					'WiFi (intérieur et dans le jardin)',
					'Serviettes de piscine fournies',
				],
				suites: [
					{
						theme: 'Suite Steampunk',
						facilities: [
							'1er étage / 21m2',
							'Lit de 180x200cm',
							'Climatisée',
							'Couette, oreillers et linge de lit de haute qualité',
							'Meubles en chêne comprenant une armoire, une commode et des tables de chevet steam-punk sur mesure',
							'Radio réveil avec chargeur sans fil /USB',
							'Rideaux occultants',
							'Sèche-cheveux',
							'Meuble double vasque avec beaucoup de rangement',
							'Serviettes de haute qualité, y compris un grand drap de bain',
							'Sèche-serviettes',
							'Grande douche aven receveur de douche plat, douche pluie thermostatique et distributeurs de produits de toilette muraux',
							'Miroir grossissant éclairé',
							'Grand miroir anti buée et éclairé',
						],
					},
					{
						theme: 'Chambre à coucher au rez-de-chaussée',
						facilities: [
							'Rez-de-chaussée / 16m2',
							'Lit de 160x200cm',
							'Plancher chauffant',
							'Couette, oreillers et linge de lit de haute qualité',
							'Chambre à coucher en chêne massif',
							'Radio réveil avec chargeur sans fil/USB',
							'Rideaux occultants',
							'Sèche-cheveux',
							'Meuble vasque avec beaucoup de rangement',
							'Serviettes de haute qualité, y compris un grand drap de bain',
							'Sèche-serviettes',
							"Grande douche à l'italienne avec douche pluie thermostatique et distributeurs de produits de toilette muraux",
							'Miroir éclairé',
							'Miroir grossissant éclairé',
						],
					},
				],
				kitchen: {
					information:
						"The Lodge offre une charmante cuisine spacieuse avec des plans de travail Silestone et beaucoup d'espace pour préparer vos plats préférés. Elle est très bien équipée avec des électroménagers de qualité et tout le nécessaire pour votre séjour dont :",
					facilities: [
						'Cuisinière Falcon Kitchener avec hotte aspirante',
						'Lave-vaisselle Bosch',
						'Réfrigérateur/congélateur Whirlpool',
						'Lave-vaisselle Whirlpool',
						'Cafetière expresso',
						'Bouilloire',
						'Four micro-onde',
						'Presse-agrumes électrique',
						'Fouet électrique',
						'Cafetière',
						'Grille-pain',
						'Un large choix de couverts, verres, ustensiles et vaisselle Denby',
					],
				},
				garden: [
					"Jardin paysager avec éclairage d'ambiance nocturne",
					"Piscine d'eau salée privée et chauffée",
					"Kiosque avec table à manger élégante et chaises/coussins (pour 6). Éclairage d'ambiance télécommandé",
					'Terrasse/solarium avec chaises longues/coussins',
					'Plancha',
					"Vues sur la forêt et magnifiques couchers de soleil à l'ouest !",
				],
			},
		},
	},
	{
		barn: {
			name: 'The Barn',
			description: '3 chambres doubles avec salle de bains',
			shortName: 'barn',
			imageFileName: 'barn-bedroom-area',
			content:
				"The Barn est une propriété de vacances luxueuse avec trois chambres doubles spacieuses chacune avec salle de bains. Chaque chambre est magnifiquement conçue avec son propre thème, y compris Animal Magic, Modern Chic et French Chic, et offre une expérience de vacances luxueuse et inoubliable. The Barn propose des installations haut de gamme, notamment une literie de haute qualité avec des oreillers en plumes d'oie, avec des produits de douche fournis dans chaque salle de bain ainsi que le plancher chauffant dans tout le rez-de-chaussée. De plus, il dispose d'une grande cuisine entièrement équipée avec une cuisinière, un lave-vaisselle, une machine à expresso et d'autres éléments essentiels pour cuisiner. Le jardin est un paradis tranquille avec une piscine privée d'eau salée chauffée, un kiosque, une terrasse et une plancha. Le jardin dispose également d'un éclairage d'ambiance nocturne et offre une vue imprenable sur la forêt et les couchers de soleil à l'ouest. Avec le WiFi à l'intérieur et dans le jardin, des adaptateurs électriques internationaux fournis et un pack de bienvenue pour vous aider à démarrer, The Barn est l'escapade idéale pour des vacances relaxantes et rajeunissantes.",
			information: {
				facilities: [
					'Toutes les chambres ont des salles de bains entièrement carrelées (climatisation au 1er étage)',
					"Literie en coton de grande qualité avec oreillers en plumes d'oie (lits faits à votre arrivée)",
					'Articles de toilette (shampooing/gel douche) fournis dans toutes les salles de bains',
					'Pack de bienvenue pour vous aider à démarrer',
					"Table à manger pouvant accueillir jusqu'à huit personnes",
					'Adaptateurs électriques internationaux',
					'Coffre-fort pour objets de valeur à code numérique',
					'Enceinte Bluetooth JBL',
					'Plancher chauffant dans tout le rez-de-chaussée',
					'Lits 18x200 ou 160x200',
					"TV écran plat 43''/108cm avec internet/chaînes internationales",
					'WiFi (intérieur et dans le jardin)',
					'Serviettes de piscine fournies',
				],
				suites: [
					{
						theme: 'Suite Magie Animale',
						facilities: [
							'1er étage / 31m2',
							'Lit de 180x200cm',
							'Climatisée',
							"TV écran plat 43''108cm avec internet/chaînes internationales",
							'Couette, oreillers et linge de lit de haute qualité',
							'Meubles en chêne de qualité comprenant une armoire, une commode et des tables de chevet',
							'Radio réveil avec chargeur sans fil/USB',
							'Meuble double vasque avec beaucoup de rangement',
							'Serviettes de haute qualité, y compris un grand drap de bain',
							'Sèche-serviettes',
							"Grande douche à l'italienne avec douche pluie thermostatique et distributeurs de produits de toilette muraux",
							'Miroir grossissant éclairé',
							'Sèche-cheveux',
							'WC séparé',
							'Fenêtre de toit Velux pour regarder les étoiles ! (avec store électrique)',
						],
					},
					{
						theme: 'Suite Chic Moderne',
						facilities: [
							'Rez-de-chaussée / 21m2',
							'Lit de 160x200cm',
							'Plancher chauffant',
							'Couette, oreillers et linge de lit de haute qualité',
							'Meubles de chambre en chêne massif',
							'Radio réveil avec chargeur sans fil /USB',
							'Radio réveil avec chargeur sans fil /USB',
							'Sèche-cheveux',
							'Portes de 90 cm de large avec poignées abaissées',
							'Poignées de maintien pour douche et toilettes',
							'Paroi de douche pliante',
							'Siège de douche disponible',
							'Meuble double vasque avec beaucoup de rangement',
							'Serviettes de haute qualité, y compris un grand drap de bain',
							'Sèche-serviettes',
							'Grand miroir antibuée et éclairé',
							"Grande douche à l'italienne avec douche pluie thermostatique et distributeurs de produits de toilette muraux",
						],
					},
					{
						theme: 'Suite French Chic',
						facilities: [
							'Rez-de-chaussée / 13m2',
							'Lit de 160x200cm',
							'Plancher chauffant',
							'Couette, oreillers et linge de lit de haute qualité',
							'Armoire, commode, chevets en chêne massif',
							'Radio réveil avec chargeur sans fil /USB',
							'Rideaux occultants',
							'Sèche-cheveux',
							'Accès direct au jardin',
							'Meuble double vasque avec beaucoup de rangement',
							'Serviettes de haute qualité, y compris un grand drap de bain',
							'Sèche-serviettes',
							"Grande douche à l'italienne avec douche pluie thermostatique et distributeurs de produits de toilette muraux",
							'Grand miroir antibuée et éclairé',
						],
					},
				],
				kitchen: {
					information:
						"The Barn est équipé d'une cuisine sur mesure avec des plans de travail en granite. Elle est très bien équipée avec des électroménagers de qualité et tout le nécessaire pour votre séjour, notamment :",
					facilities: [
						'Cuisinière Falcon Kitchener Range avec hotte aspirante Electrolux',
						'Lave-vaisselle Bosch',
						"Réfrigérateur/congélateur Whirlpool avec distributeur d'eau",
						'Lave-linge/sèche-linge LG',
						'une cafetière expresso',
						'Bouilloire',
						'Four micro-onde',
						'Fouet/mixeur électrique',
						'Presse-agrumes électrique',
						'Cafetière',
						'Grille-pain',
						'Casier à vin en chêne',
						'Un large choix de couverts, verres, ustensiles et vaisselle Denby',
					],
				},
				garden: [
					"Jardin paysagé avec éclairage d'ambiance nocturne",
					"Piscine d'eau salée privée et chauffée",
					"Kiosque avec table à manger élégante et chaises/coussins (pour 8). Éclairage d'ambiance/salle à manger télécommandé",
					'Terrasse/solarium avec chaises longues/coussins',
					'Plancha',
					"Vues sur la forêt et magnifiques couchers de soleil à l'ouest !",
				],
			},
		},
	},
];

export default async function getGites(req, res) {
	res.status(200).json(gites_en);
}
